"$schema" = "./node_modules/wrangler/config-schema.json"
name = "jordan-page-dev"
main = ".open-next/worker.js"
compatibility_date = "2026-02-27"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
